-- general
require ("general.options")
require ("general.keymaps")
-- plugins
require ("plugins.plugins")
-- configs plugins
-- interface
require ("plugins.configs.interface.barbar")
require ("plugins.configs.interface.colorizer")
require ("plugins.configs.interface.dracula")
require ("plugins.configs.interface.indent-blanklines")
require ("plugins.configs.interface.lualine")
-- code
require ("plugins.configs.code.autopairs")
require ("plugins.configs.code.cmp")
require ("plugins.configs.code.comment")
require ("plugins.configs.code.copilot")
require ("plugins.configs.code.lsp")
-- keymaps
require ("plugins.configs.keymaps")
-- other
require ("plugins.configs.others.nvim-tree")
require ("plugins.configs.others.telescope")
require ("plugins.configs.others.treesitter")
